version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "goallery_db"
    environment:
      POSTGRES_USER: goallery
      POSTGRES_PASSWORD: goallery
      POSTGRES_DB: goallery
      PGDATA: /pgdata
    ports:
      - "54321:5432"
    volumes:
      - ./pgdb-init.sql:/docker-entrypoint-initdb.d/init.sql
      - .pgdata:/pgdata

